name: Build and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write # Needed for creating tags and releases
  pull-requests: write # For commenting on PRs if needed

env:
  PLAYDATE_SDK_VERSION: "2.6.2"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      sdk-path: ${{ steps.set-path.outputs.sdk-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for proper versioning

      - name: Cache Clang 17
        id: cache-clang
        uses: actions/cache@v4
        with:
          path: ~/clang17
          key: ${{ runner.os }}-clang-17-bin

      - name: Install Clang 17
        if: steps.cache-clang.outputs.cache-hit != 'true'
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc > /dev/null
          sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main"
          sudo apt-get update
          sudo apt-get install -y clang-17
          mkdir -p ~/clang17
          cp /usr/bin/clang-17 ~/clang17/clang
          cp /usr/bin/clang++-17 ~/clang17/clang++
          chmod +x ~/clang17/clang ~/clang17/clang++

      - name: Setup Clang
        run: |
          if [ -d "$HOME/clang17" ]; then
            chmod +x $HOME/clang17/clang $HOME/clang17/clang++
            echo "$HOME/clang17" >> $GITHUB_PATH
          else
            echo "Error: Clang cache directory not found"
            exit 1
          fi

      - name: Build nob
        run: |
          clang .nob/nob.c -o nob
          chmod +x ./nob

      - name: Cache PlaydateSDK
        id: cache-playdate-sdk
        uses: actions/cache@v4
        with:
          path: ~/PlaydateSDK
          key: ${{ runner.os }}-playdate-sdk-${{ env.PLAYDATE_SDK_VERSION }}

      - name: Download and setup PlaydateSDK
        if: steps.cache-playdate-sdk.outputs.cache-hit != 'true'
        run: |
          wget -O playdate-sdk.tar.gz "https://download.panic.com/playdate_sdk/Linux/PlaydateSDK-${{ env.PLAYDATE_SDK_VERSION }}.tar.gz"
          mkdir -p $HOME/PlaydateSDK
          tar -xf playdate-sdk.tar.gz --strip-components=1 -C $HOME/PlaydateSDK
          rm playdate-sdk.tar.gz
          echo "sdk-path=~/PlaydateSDK" >> $GITHUB_OUTPUT

      - name: Generate bundle
        run: |
          PLAYDATE_SDK_PATH=~/PlaydateSDK ./nob bundle

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./nob
            ./dist/pdphyzx.h

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Set permissions
        run: chmod +x ./nob

      - name: Cache PlaydateSDK
        uses: actions/cache@v4
        with:
          path: ~/PlaydateSDK
          key: ${{ runner.os }}-playdate-sdk-${{ env.PLAYDATE_SDK_VERSION }}

      - name: Run tests
        run: |
          PLAYDATE_SDK_PATH=~/PlaydateSDK ./nob test --no-bundle

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Set permissions for nob
        run: chmod +x ./nob

      - name: Cache PlaydateSDK
        uses: actions/cache@v4
        with:
          path: ~/PlaydateSDK
          key: ${{ runner.os }}-playdate-sdk-${{ env.PLAYDATE_SDK_VERSION }}

      - name: Build example projects
        run: |
          PLAYDATE_SDK_PATH=~/PlaydateSDK ./nob build --no-bundle

  release:
    needs: [test, build]
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            .github

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Bump version and push tag
        id: version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add version info to header file
        if: steps.version.outputs.new_tag != ''
        run: |
          HEADER_COMMENT="/*\n * pdphyzx.h - Version ${{ steps.version.outputs.new_tag }}\n * Released under MIT License\n * https://github.com/${{ github.repository }}/releases/tag/${{ steps.version.outputs.new_tag }}\n */\n\n"
          TEMP_FILE=$(mktemp)
          echo -e "$HEADER_COMMENT" > "$TEMP_FILE"
          cat ./dist/pdphyzx.h >> "$TEMP_FILE"
          mv "$TEMP_FILE" ./dist/pdphyzx.h

      - name: Release
        if: steps.version.outputs.new_tag != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          name: Release ${{ steps.version.outputs.new_tag }}
          files: ./dist/pdphyzx.h
          body: ${{ steps.version.outputs.changelog }}
